
services:
  satu-api-prod:
    image: satu-api-prod:latest
    restart: always
    build:
      context: .
      args:
        NODE_ENV: 'production'
        NODE_PORT: '80'
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - 6001:80
    expose:
      - '80'
    volumes:
      - /usr/app/storage/prod/upload/:/app/public/upload
      - /usr/app/storage/prod/export/:/app/public/export
      - /usr/app/storage/prod/assets/:/app/public/assets
      - /usr/app/storage/prod/logs/:/app/logs
    command: yarn start
    networks:
      - network-db
      - network-prod

networks:
  network-db:
    name: network-db
    external: true
  network-prod:
    name: network-prod
    external: true